# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KnxExporter < Formula
  desc "The KNX Prometheus Exporter is a small bridge to export values measured by KNX sensors to Prometheus."
  homepage "https://github.com/chr-fritz/knx-exporter"
  version "1.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chr-fritz/knx-exporter/releases/download/v1.2.3/knx-exporter_1.2.3_darwin_amd64.tar.gz"
      sha256 "3095011d95d105a41ade6231821c1c372bbd1cf20e0aa71f69840a47731987ab"

      def install
        bin.install "knx-exporter"
        bash_completion.install "completions/knx-exporter.bash" => "knx-exporter"
        zsh_completion.install "completions/knx-exporter.zsh" => "_knx-exporter"
        fish_completion.install "completions/knx-exporter.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chr-fritz/knx-exporter/releases/download/v1.2.3/knx-exporter_1.2.3_darwin_arm64.tar.gz"
      sha256 "885ad32954c359fc90be4d69494c03d6c08aaa58fd555f0fb888c7bf3cbe4c0e"

      def install
        bin.install "knx-exporter"
        bash_completion.install "completions/knx-exporter.bash" => "knx-exporter"
        zsh_completion.install "completions/knx-exporter.zsh" => "_knx-exporter"
        fish_completion.install "completions/knx-exporter.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chr-fritz/knx-exporter/releases/download/v1.2.3/knx-exporter_1.2.3_linux_amd64.tar.gz"
      sha256 "ebab1ae164f7bf3f36869dd40a2df6ead436a8f6de8d2e1cfae1ffaef2e350ff"
      def install
        bin.install "knx-exporter"
        bash_completion.install "completions/knx-exporter.bash" => "knx-exporter"
        zsh_completion.install "completions/knx-exporter.zsh" => "_knx-exporter"
        fish_completion.install "completions/knx-exporter.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chr-fritz/knx-exporter/releases/download/v1.2.3/knx-exporter_1.2.3_linux_arm64.tar.gz"
      sha256 "e101537f5a7b0c50e93a811b3c697c4333067b135a8417cbc18172ec760a01ef"
      def install
        bin.install "knx-exporter"
        bash_completion.install "completions/knx-exporter.bash" => "knx-exporter"
        zsh_completion.install "completions/knx-exporter.zsh" => "_knx-exporter"
        fish_completion.install "completions/knx-exporter.fish"
      end
    end
  end

  test do
    system "#{bin}/knx-exporter --version"
  end
end
