# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KnxExporter < Formula
  desc "The KNX Prometheus Exporter is a small bridge to export values measured by KNX sensors to Prometheus."
  homepage "https://github.com/chr-fritz/knx-exporter"
  version "0.1.1"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/chr-fritz/knx-exporter/releases/download/v0.1.1/knx-exporter_0.1.1_darwin_amd64.tar.gz"
    sha256 "de350c23b31acb67387323c72d183f4424e9a714fc84a8cf6d99ff36d2e875ac"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/chr-fritz/knx-exporter/releases/download/v0.1.1/knx-exporter_0.1.1_linux_amd64.tar.gz"
    sha256 "414e209870df2f64aa170f15754eec5d9af2bc05a0b4cec94db14e0d08b6c3b1"
  end

  def install
    bin.install "knx-exporter"
    bash_completion.install "completions/knx-exporter.bash" => "knx-exporter"
    zsh_completion.install "completions/knx-exporter.zsh" => "_knx-exporter"
  end

  test do
    system "#{bin}/knx-exporter --version"
  end
end
