# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KnxExporter < Formula
  desc "The KNX Prometheus Exporter is a small bridge to export values measured by KNX sensors to Prometheus."
  homepage "https://github.com/chr-fritz/knx-exporter"
  version "1.2.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chr-fritz/knx-exporter/releases/download/v1.2.6/knx-exporter_1.2.6_darwin_amd64.tar.gz"
      sha256 "46f35361aa2d3f6240c10d0b2a134b5063b72500902a78e1c896f6103bfa53d3"

      def install
        bin.install "knx-exporter"
        bash_completion.install "completions/knx-exporter.bash" => "knx-exporter"
        zsh_completion.install "completions/knx-exporter.zsh" => "_knx-exporter"
        fish_completion.install "completions/knx-exporter.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chr-fritz/knx-exporter/releases/download/v1.2.6/knx-exporter_1.2.6_darwin_arm64.tar.gz"
      sha256 "edff9cb8d98a20ef646ee0b5c22b72048180d014c58611b0281da62c8073986b"

      def install
        bin.install "knx-exporter"
        bash_completion.install "completions/knx-exporter.bash" => "knx-exporter"
        zsh_completion.install "completions/knx-exporter.zsh" => "_knx-exporter"
        fish_completion.install "completions/knx-exporter.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chr-fritz/knx-exporter/releases/download/v1.2.6/knx-exporter_1.2.6_linux_amd64.tar.gz"
      sha256 "13edc21193c426287b444250cc689a656129e38515e1a727eda0aeacea6bd859"
      def install
        bin.install "knx-exporter"
        bash_completion.install "completions/knx-exporter.bash" => "knx-exporter"
        zsh_completion.install "completions/knx-exporter.zsh" => "_knx-exporter"
        fish_completion.install "completions/knx-exporter.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chr-fritz/knx-exporter/releases/download/v1.2.6/knx-exporter_1.2.6_linux_arm64.tar.gz"
      sha256 "764ae1144109c0b5297604ac1d59b66277f07d51dd1f83d8b42d066f18bd70b8"
      def install
        bin.install "knx-exporter"
        bash_completion.install "completions/knx-exporter.bash" => "knx-exporter"
        zsh_completion.install "completions/knx-exporter.zsh" => "_knx-exporter"
        fish_completion.install "completions/knx-exporter.fish"
      end
    end
  end

  test do
    system "#{bin}/knx-exporter --version"
  end
end
